# Úvod do jazyka Python

Tato přednáška přestavuje stručný úvod do programovacího jazyka Python. Probrány jsou jak základní tak pokročilejší nástroje, které budou používány po zbytek kurzu. Pro zájemce o hlubší porozumění Pythonu doporučuji kurz [Vědecké programování v Pythonu](https://fjfi.pythonic.eu/) (12PYTH), ze kterého tato přednáška čerpá.

Další užitečný kurz v češtině je například od [Pyladies](https://naucse.python.cz/course/pyladies/).

(install-all)=
## Instalace Pythonu a prostředí Jupyter notebook

V druhé části kurzu Numerických metod budeme používat moderní prostědí [Jupyter notebook](https://jupyter.org/) (soubory s koncovkou `.ipynb`), které jsou velmi vhodné jak na výuku tak na rychlé otestování a prototipování kódu.

Máte volbu mezi dvěmi možnostmi, jak sledovat přednášku a mít možnost spouštět kód:
1. Pracovat v *online* interaktivním prostředí - *Binder*, ***JupiterHub FJFI***, *Google Colab*
2. Pracovat *lokálně* na svém počítači

### Postup instalace

**Online interaktivní prostředí** (doporučuji)

Pro spuštení interaktivní verze této stránky klikněte ve vrchním menu na <i class="fas fa-rocket" aria-hidden="true"></i> a zvolte:
* *Binder* - ve kterém lze <i>Jupyter notebook</i> (JP) upravovat a následně uložit na disk
* *JupyterHub* - místní prostědí běžící u nás na FJFI, umožňuje **uložit** ve vlastním účtu
* *Google Colab* - na vlastní nebezpečí

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #F4330C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #F7C8C0; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Pozor</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Spuštění prostředí *Binder* může trvat několik desítek sekund. Jupyter notebook je v tomto prostředí uložen pod dočasným URL. Při zavření okna se postup ztratí! Je nutné tedy upravený soubor před zavřením okna stáhnout. 
</p>
</div>
</div>

**Lokální prostření**

Pro programování na svém počítači je třeba:
1. Nainstalovat [Python](https://www.python.org/downloads/) (často již nainstalován s OS)
2. Nainstalovat [Jupyter notebook](https://jupyter.org/install)
4. Stáhnout repozitář z GitHubu (ve vrchním menu tlačítko <i class="fab fa-github" aria-hidden="true"></i>)
5. Pak příkazem `> jupyter notebook` se spustí prostědí v prohlížeči.

Jako alternativu doporučuji použít IDE (Integrated Development Environment) [Visual Studio Code](https://code.visualstudio.com/), ve kterém je možné přidat rozšíření pro [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) a [Jupyter notebook](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter).
Také je možné přímo stáhnout GitHub repozitáře přes [odpovídající rozšíření](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github).



<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Další možnosti instalace nástrojů jsou popsány [zde](https://fjfi.pythonic.eu/posts/nastroje.html#Doporu%C4%8Den%C3%A1-sada-n%C3%A1stroj%C5%AF).

Pro pokročilé možnosti *virtuálních prostředí* postupujte podle postupu [zde](https://fjfi.pythonic.eu/posts/prvni-krucky.html#Virtu%C3%A1ln%C3%AD-prost%C5%99ed%C3%AD) nebo [zde](https://valenpe7.github.io/numerical_methods/README.html#run-the-notebooks-offline).
</p>
</div>
</div>

## Jupyter notebook
```
* definice, použití, výhody a nevýhody
```

Jupyter notebook je interaktivní dokument obsahující buňky se spustitelným kódem, textem, obrázky, vzorci a apod. Je to velmi vhodný nástroj pro výuku a proto všechen materiál k tomuto cvičení je ve formě těchto notebooků.

V této kapitolce se krátce seznámíme, jak se s Jupyter notebooky pracuje. Podrobný popis všech vychytávek si můžete přečíst [zde](https://realpython.com/jupyter-notebook-introduction/).

### Hello world!

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #E0B32C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #FFF3CD; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Úkol</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Napište `print("Hello world!")` a stiskněte `Shift` `+` `Enter` (nebo `Ctrl` `+` `Enter`)
</p>
</div>
</div>

In [1]:
## DOPLŇTE ##

Pomocí klávesy `b` vložíte další řádek do JP.
* Stiskněte `b`.

Odstranění řádku: vyberte řádek v JP a stiskněte `d` `+` `d`

Klávesou `a` vložíte nový řádek nad právě vybraný.

Přidání buňky s textem:
1. Stiskněte `a`. 
2. Vyberte tento nový řádek a stiskněte `m`. Nyní lze do řádku místo kódu zapisovat text.

Pokud chcete řádek převést na kód, stiskněte `y`.



<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Pro nápovědu možných funkcí stiskněte `Tab`.

Pro zobrazení dokumentace k vybrané funkci stiskněte `Shift`+`Tab`.
</p>
</div>
</div>

## Jazyk Python
Python je univerzální programovací jazyk, hojně používaný vědeckou komunitou. Existuje spousta knihoven řešící celou řadou úloh za vás. Některé nejpoužívanější knihovny si v tomto kurzu ukážeme.

Základní vlastnosti Pythonu (vs C++):
* *Dynamicky typovaný* jazyk - typ proměnné se určuje až při běhu programu
* *Silně typovaný* (strongly typed) jazyk - vše má jasně definovaný typed
* *Interpretovaný* jazyk - kód v Pythonu není kompilován, až při běhu dochází k jeho interpretaci
* Obsahuje rozsáhlou *vestavěnou knihovnu modulů* a funkcí
* Přehledná, jednoduchá a čitelná *syntaxe*
* Objekově orientovaný + funkcionální programování

### Komentáře

Jednořádkový komentář se zadává za znak `#`, více řádků lze zakomentovat obklopením `"""`:

In [2]:
# toto je komentar
"""
Komentar
na vice
radku...
"""
print("Hello world!") 
#print("Hello world not printed!") 

Hello world!


### Základní aritmetické operace

Inicializace proměnných `a`, `b`, základní aritmetické operace a výpis výsledku pomocí funkce `print()`:

In [3]:
a = 43
b = 5.0

soucet = a + b
rozdil = a - b
soucin = a * b
podil = a / b
podil_beze_zbytku = a // b

mocnina = a**b    # v C++ pow()
zbytek_po_deleni = a % b

# vypis
print('Součet ', soucet)
print('Rozdíl ', rozdil)
print('Součin ', soucin)
print('Podíl ', podil)
print('Podíl beze zbytku ', podil_beze_zbytku)

print('Mocnina ', mocnina)
print('Zbytek po dělení ', zbytek_po_deleni)

Součet  48.0
Rozdíl  38.0
Součin  215.0
Podíl  8.6
Podíl beze zbytku  8.0
Mocnina  147008443.0
Zbytek po dělení  3.0


### Podmínky - if, else a elif

Za klíčovými slovy `if` a `else` musíme psát `:`.

In [4]:
cislo = 0

if cislo > 0:
    print(cislo, "je kladne.")
elif (cislo < 0):    # logický výraz může být uzavřen závorky
    print(cislo, "je zaporne")
else:
    print("musi to byt nula")

print("Tento text se vypise vzdy.")

musi to byt nula
Tento text se vypise vzdy.


<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #F4330C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #F7C8C0; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Pozor</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Vnitřní bloky kódu se v Pythonu **odsazují** o `tab` nebo **čtyři mezery**! (V C++ je block uzavřen závorky `{` a `}`, a odsazení může být libovolné.)
</p>
</div>
</div>

Logické hodnoty jsou `True` a `False`, operátory pro složitější logické výrazy jsou `or`, `and` a `not`.

In [5]:
x = 4
print(x > 1 and x < 3, x == 3 or x == 4)

print(True == (not False))

False True
True


### Základní datové struktury

**String** (řetězec)

In [6]:
a = 3 * ("Abc%i" % 3) + "!"    # string lze vytvořit například takto
print(a)

Abc3Abc3Abc3!


In [7]:
# různé způsoby tisku čísla a textu
cislo = 37

print("cislo = " + str(cislo))
print("cislo = %i" % cislo)
print(f"cislo = {cislo}, cislo^2 = {cislo**2}")
print("cislo = {0}, cislo^2 = {1}".format(cislo, cislo**2))

cislo = 37
cislo = 37
cislo = 37, cislo^2 = 1369
cislo = 37, cislo^2 = 1369


**Konverze typů**

Každá proměnná má v Pythonu jasně definovaný typ.

In [8]:
x = 4
print(x, type(x))

s = "text"
print(s, type(s)) 

4 <class 'int'>
text <class 'str'>


Mezi datovými typy je možné přecházet pomocí speciálních funkcí:

In [9]:
int("3")        # string -> int
float("3.14")   # string -> float
str(3.14)       # float -> string

'3.14'

### Kontejnery

Kontejnery jsou datové struktury obsahující větší počet prvků.
Mezi základní patří:
* `tuple` - *neměnitelný* seznam (pole)
* `list` - *měnitelný* seznam (pole)
* `dics` - *asociativní* pole
* `set` - množina prvků

Dále uvidíme, že:
* Prvky nemusejí být stejného typu!
* Pro indexování (přístup k jednotlivým prvkům) se používají závorky `[]` a indexuje se od **0**.

**Tuple**

Tuple je n-tice prvků, které po vytvoření nelze měnit!

In [10]:
tuple1 = (1, 'a', 5)           # Základní syntax vytváření tuple (kulaté závorky)
tuple2 = 1, 'a'                # Závorky nejsou povinné, ale... !
tuple3 = tuple(["a", "b"])     # Pokročilé: Vytvoření tuple z jiného kontejneru
tuple4 = tuple(range(0, 10))   # Pokročilé: Vytvoření tuple z iterátoru / generátoru
tuple5 = ()                    # Prázdný tuple
tuple6 = ("single", )          # Tuple s jedním prvkem
tuple7 = 0, "1", (0, 1, 2)     # Tuple může pochopitelně obsahovat další tuple

print(f"tuple1={tuple1}")
print(f"tuple2={tuple2}")
print(f"tuple3={tuple3}")
print(f"tuple4={tuple4}")
print(f"tuple5={tuple5}")
print(f"tuple6={tuple6}")
print(f"tuple7={tuple7}")

tuple1=(1, 'a', 5)
tuple2=(1, 'a')
tuple3=('a', 'b')
tuple4=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
tuple5=()
tuple6=('single',)
tuple7=(0, '1', (0, 1, 2))


In [11]:
print(tuple4[0])         # První prvek
print(tuple4[-1])        # Poslední prvek
print(tuple4[-2])        # Předposlední prvek

0
9
8


Vyzkoušejte, že skutečně není možné přepsat prvky `tuple`:

In [12]:
#tuple1[0] = 58

V praxi se s tímto typem setkáte při volání funkcí, které vrací více hodnot. Odpovídající proměnné je pak možné *rozbalit* následujícím způsobem: 

In [13]:
def dvecisla():
    return 37, 58

a, b = dvecisla()   # rozbalení tuplu
print(a, b)

37 58


**List**

List je opět n-tice prvků, ale oproti `tuple` je možné prvky měnit. Odpovídá polím (array) v C++. Navíc ale může obsahovat prvky různých typů!

In [14]:
list(), []                 # prázdný list
list1 = ["a", "b", "c"]    # list vytvoříme pomocí [...]
list2 = [0, 0.0, "0.0"]    # můžeme tam dát libovolné typy
list3 = list(tuple1)       # nebo list vytvořit z tuple

print(list1)
print(list2)
print(list3)

['a', 'b', 'c']
[0, 0.0, '0.0']
[1, 'a', 5]


Jazyk Python poskytuje tyto základní operace pro práci se seznamy:

In [15]:
# všechny dostupné funkce pro operace s polem
", ".join(item for item in dir(list) if not item.startswith("_"))

'append, clear, copy, count, extend, index, insert, pop, remove, reverse, sort'

In [16]:
list1.append("d")         # přidání prvku
print(list1)              # list1 se změnil!
list1.sort(reverse=True)
print(list1)
print(list1.pop())        # vyjme poslední prvek
print(list1)

list1.remove("d")         # odstranění prvku(ů)
print(list1)

['a', 'b', 'c', 'd']
['d', 'c', 'b', 'a']
a
['d', 'c', 'b']
['c', 'b']


U kontejnerů typu `tuple` a `list` lze provádět výběr více prvků najednou pomocí **řezů** podle pravidla:
```
[[dolní_mez] : [horní_mez] : [krok]]
```

In [17]:
l = list(range(10))

print(l[:])     # vyber všechny prvky
print(l[0:2])   # vyber první 2 prvky
print(l[:5])    # vyber prvních 5 prvků
print(l[1:7])   # vyber prvky 1-6
print(l[5:])    # vyber všechny prvky od indexu 5 dál 
print(l[-3:])   # poslední tři prvky

print(l[::2])   # sudé prvky

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]
[5, 6, 7, 8, 9]
[7, 8, 9]
[0, 2, 4, 6, 8]


**Dict** a **Set**

Tyto kontejnery používat typicky v kurzu nebudeme. Zájemci se o nich můžou vzdělat opět [zde](https://fjfi.pythonic.eu/posts/kontejnery.html).

### Opakování - cykly

**For**

Zde využijeme funkci `range(min,max,krok)`, která vytvoří sekvenci celých čísel od `min` po `max` ***(prvek max není v sekvenci obsažen)*** s uvedeným krokem. Výchozí hodnoty jsou `min = 0` a `krok = 1`.
Tuto funkci lze použít několika různými způsoby:

In [18]:
print(list(range(10)))
print(list(range(0, 10)))
print(list(range(0, 10, 1)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
pole = [1,2,4,8,16]    # procházení pole verze 1
for i in range(len(pole)):
    print(pole[i])

1
2
4
8
16


**Foreach**

Další způsob procházení pole je pomocí *foreach* konstrukce, která v Pythonu má stejný zápis:

In [21]:
pole = [1,2,4,8,16]    # procházení pole verze 2
for x in pole:
    print(x)

1
2
4
8
16


**While**

Dalším typem cyklu je `while` cyklus, který běží dokud je splněna určitá podmínka.

In [22]:
x = 0
while x < 10:
  print(x)
  x = x + 1

0
1
2
3
4
5
6
7
8
9


<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

`x = x + 1` je možné napsat zkratkou pomocí `x += 1` (ovšem C++ operátor `x++` v Pythonu použít nelze!).
</p>
</div>
</div>

**Continue**

Pomocí příkazu `continue` lze přeskočit zbytek iterace v cyklu a skočit na další:

In [23]:
a = 0
while a < 5:
    a += 1
    if a % 2 == 0:    # sudá čísla nebudeme vypisovat
        continue
    print("a = %i" % a)
else:
    a = 1
print("Konec, a = %i" % a)

a = 1
a = 3
a = 5
Konec, a = 1


**Break**

Pomocí příkazu `break` lze předčasně ukončit cyklus:

In [24]:
# pomocí break najdeme největší trojciferené číslo dělitelné 19ti
a = 999
while a > 0:
    if a % 19 == 0:
        print("Výsledek je: %i" % a)
        break
    a -= 1
else:
    # break nespustí else část
    print("Nic jsme nenašli")

Výsledek je: 988


<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #276BE9; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #DCE7FC; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Poznámka</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

V Pythonu je možné psát `else` blok za `while` cyklus, který se spustí ve chvíli, kdy je podmínka `False`.
</p>
</div>
</div>

### Definice vlastní funkce

Vlastní funkce se definují pomocí hesla `def`. Ukážeme si to na výpočtu faktoriálu pomocí rekurze:

In [25]:
def factorial(n):
    if (n < 2):
        return n
    return n*factorial(n-1)

factorial(10)

3628800

### Další základní funkce
Python obsahuje několik základních funkcí, které se běžně při psaní kódu používají.
Celý jejich seznam můžete nalézt [zde](https://docs.python.org/3.12/library/functions.html).
Tady je výtah těch nejběžnějších, které se nám budou hodit:
* `dir()` - vrací seznam dostupných funkcí
* `print()` - výpis na standartní výstup
* `len()` - vrací délku řetězce
* `range()` - vrací sekvenci/pole po sobě jdoucích čísel
* `input()` - čtení standartního vstupu
* `str()` - převod proměnné (čísla) na řetězec (string)
* `int()` - převod řetezce na celé číslo
* `float()` - převod řetezce na desetinné číslo
* `type()` - vrací typ proměnné
* `open()` - otevření souboru
* `close()` - zavření souboru


<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #E0B32C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #FFF3CD; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Úkol</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Vyžádejte si od uživatele číslo pomocí funkce `input()` a vytiskněte jeho druhou mocninu.
</p>
<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Budete potřebovat také funkci `int()` nebo `float()`.
</p>
</div>
</div>
</div>
</div>

In [26]:
### DOPLŇTE ###

### Import knihoven
Pro využití určité knihovny v kódu je třeba danou knihovnu importovat.
Například knihovnu pro různé matematické funkce přidáme pomocí `import math` (v C++ ekvivalentní `#include <math.h>`).

In [27]:
import math    # chceme načíst vestavěný modul math

print(math.sin(math.pi / 4))    # použijeme funkci sin a konstantu pi

0.7071067811865476


Využívání knihovny je možné usnadnit specifikováním, které funkce (proměnné) chceme importovat:

In [28]:
from math import sin, pi    # import pouze některých položek

print(sin(pi / 4))

0.7071067811865476


Nebo můžeme místo jména knihovny zadefinovat alias: 

In [29]:
import math as m

print(m.sin(m.pi / 4))

0.7071067811865476


In [30]:
m.factorial(10)    # volání funkce faktorial z knihovny math

3628800

## Knihovna numpy
* popis knihovny, využití
* jednotlivé operace, rozdíl oproti normálnímu poli
* typy, přetypování, matice, atd.
* ukázka na úlohách z předchozích přednášek..


Tipy
* klavesova zkratka `Tab` -> vyvolani napovedy
* klavesova zkratka `Shift`+`Tab` -> vyvolani dokumentace

[NumPy](http://www.numpy.org/) je základní Python knihovna pro práci s *numerickými daty*, konkrétně s 1- až n-rozměrnými maticemi. Implementace je z velké části napsána v C a Fortranu a používá BLAS knihovny. Numpy tak umožňuje pracovat s numerickými daty ve stylu Python kontejnerů (existují samozřejmě rozdíly) a zároveň zachovat rychlost kompilovaných jazyků.

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Numerické knihovny implementovány v rychlém jazyce (C, Fortran) pomocí optimalizovaných a odladěných algoritmů. Proto používání již implementovaných funkcí není jen pohodlnější, ale vede na významně rychlejší kód!

Je dobrá praxe snažit se vyhnout používání cyklů tam, kde lze využít některou z knihovních funkcí (jednoduchý příklad - násobení dvou polí po prvcích).
</p>
</div>
</div>

V této kapitolce se načíte:
* Jak pracovat s poli a maticemi v knihovně `numpy`.
* Jak provádět různé algebraické operace.
* Jak efektivně pracovat s daty pomocí různých triků.

In [1]:
import numpy as np  # import knihovny numpy

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Pro nápovědu možných funkcí v knihovně `numpy` stiskněte `Tab` po napsaní `np.`.

Pro zobrazení dokumentace k vybrané funkci klikněte na funkci a stiskněte `Ctrl` nebo `Shift`+`Tab` (`Ctrl`+`Space` vs VS Code).
</p>
</div>
</div>

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #E0B32C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #FFF3CD; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Úkol</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Vyzkoušejte si používání nápovědy a dokumentace. Najděte funkci, která vrátí diagonální matici s posloupoností čísel (1, 2, 3) na diagonále.

Co dělá funkce `np.diagonal()`?
</p>
</div>
</div>

In [5]:
### DOPLŇTE ###

### Numpy array

Vytváření pole (obdoba `list`) je v knihovně `numpy` možné několika způsoby:
* Z již existujícího kontejneru (`list` nebo `tuple`).
* Pomocí knihovní funkce, která pole vygeneruje podle daného pravidla (`arange()`, `ndarray()`, `zeros`, ...).
* Načtením ze souboru.

In [29]:
vector = np.array([1, 2, 3, 4])
vector

array([1, 2, 3, 4])

In [30]:
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

Proměnné `vector` a `matrix` jsou stejného typu (`ndarray`), ale liší se rozměrem - `shape`.

In [31]:
print(type(vector), type(matrix))

print(vector.shape, matrix.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(4,) (2, 2)


Celkový počet prvků lze získat pomocí `size`, zatímco dimenze pole pomocí `ndim`:

In [32]:
print("size: %i" % vector.size, "dim: %i" % vector.ndim)

print(f"size: {matrix.size}", f"dim: {matrix.ndim}")

size: 4 dim: 1
size: 4 dim: 2


**Numpy array vs list**

Pole v knihovně `numpy` mají několik zásadních výhod pro numerické výpočty:
* Python seznamy (`list`) jsou příliž obecné, dynamicky typované a nepodporují matematické funkce.
* V `numpy` jsou pole staticky typované a homogenní - při vytvoření je určen typ, který je jednotný pro všechny prvky.
* Efektivní uložení v paměti, implementace matematických operací v rychlém jazyce (C, Fortran).

In [33]:
matrix.dtype

dtype('int32')

In [34]:
matrix_c = np.array([[1, 2], [3, 4]], dtype=complex)
matrix_c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Změnit typ lze vytvořením nové kopie pole nebo přes speciální funkce knihovny Numpy (`np.int32()`, `np.float32()`, ...):

In [35]:
matrix[1,1] = 5.5
print(matrix[1,1])

matrix = np.array(matrix, dtype=float)
matrix[1,1] = 5.5
matrix[1,1]

5


5.5

In [37]:
matrix = np.float32(matrix)
matrix

array([[1. , 2. ],
       [3. , 5.5]], dtype=float32)

**Pomocné generátory polí**

V Numpy existuje množství pomocných funkcí, které výrazně zesnadňují vytváření polí:

`arange` vygeneruje posloupnost, syntaxe je stejná jako `range`:

In [28]:
np.arange(0, 10, 1)  # argumenty: start, stop, step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(-1, 0, 0.1)

array([-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1])

`linspace` a `logspace` vytváří posloupnosti s daným počtem prvků (budou se hodit obzvlášť při různých vizualizacích dat):

In [30]:
np.linspace(0, 10, 5)   # argumenty: start, stop, počet

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.logspace(0, 10, 11, base=10)   # argumenty: start, stop, počet, základ logaritmu

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])

`ones` a `zeros` vytvoří pole ze samých nul nebo jedniček:

In [32]:
np.ones(3)

array([1., 1., 1.])

Pokud chceme 2 a více rozměrů, musíme zadat rozměr jako `tuple` nebo `list`:

In [39]:
np.zeros([2, 3]), np.zeros((2, 3), dtype=int)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[0, 0, 0],
        [0, 0, 0]]))

**Indexování**

Přístup k prvkům pole je analogický jako u Python seznamů. Pole jde stejným způsobem *řezat*.

In [43]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]], dtype=int)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
matrix[1, 1]    # prvek na indexu (1,1)

6

Řez vybraným řádkem nebo sloupcem:

In [45]:
matrix[1, :]    # řez druhým řádkem

array([5, 6, 7, 8])

In [46]:
matrix[:, 1]    # řez druhým sloupcem

array([ 2,  6, 10, 14])

Řezy jsou **mutable**: pokud do nich něco přiřadíme, projeví se to na původním objektu:

In [47]:
matrix[:, 0] = 0
matrix

array([[ 0,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0, 10, 11, 12],
       [ 0, 14, 15, 16]])

In [48]:
matrix[:, 0] = np.arange(4)
matrix

array([[ 0,  2,  3,  4],
       [ 1,  6,  7,  8],
       [ 2, 10, 11, 12],
       [ 3, 14, 15, 16]])

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #E0B32C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #FFF3CD; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Úkol</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Vyberte libovolnou submatici matice `matrix` o velikosti 2x2, transponujte ji a změnu uložte do původní matice.
</p>
</div>
</div>

In [49]:
### DOPLŇTE ###

**Vyřezávání pomocí pole indexů**

V Numpy je navíc možné řezat pomocí pole indexů:

In [50]:
matrix[[1,3], :]    # výběr 2. a 4. řádku 

array([[ 1,  6,  7,  8],
       [ 3, 14, 15, 16]])

Výběr pomocí masky:

In [54]:
matrix[[[True,False,False,True], 
        [False,False,False,False], 
        [False,False,False,False], 
        [True,False,False,True]]]   # výběr rohových prvků

array([ 0,  4,  3, 16])

In [53]:
matrix[matrix % 3 == 0] # výběr prvků dělitelných 3

array([ 0,  3,  6, 12,  3, 15])

**Append** a **Insert**

Podobně jako u Python polí, Numpy poskytuje funkce na přidání prvku nakonec `append()` a na daný index `insert()`:

In [ ]:
array = np.arange(5)

array1 = np.append(array, -1)
array1

array([ 0,  1,  2,  3,  4, -1])

In [ ]:
array2 = np.insert(array, 2, -1)
array2

array([ 0,  1, -1,  2,  3,  4])

### Maticové operace

Součet/rozdíl matice a skaláru:

In [18]:
np.ones((3, 3)) + 1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

Násobení/dělení skalárem:

In [17]:
np.arange(0, 5) * 2

array([0, 2, 4, 6, 8])

In [16]:
np.ones((3, 3)) / 4

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

Násobení matic a vektorů se provádí pomocí funkce `dot` nebo operátoru `@`:

In [19]:
# matice 2x3
A = np.array([[1,2,3],[4,5,6]])
print(A, A.shape, "\n")

# matice 3x2
B = np.array([[1,2],[3,4],[5,6]])
print(B, B.shape, "\n")

[[1 2 3]
 [4 5 6]] (2, 3) 

[[1 2]
 [3 4]
 [5 6]] (3, 2) 



In [23]:
C = np.dot(A,B) # součin matic
C, C.shape

(array([[22, 28],
        [49, 64]]),
 (2, 2))

In [22]:
C = A @ B # součin matic
C

array([[22, 28],
       [49, 64]])

In [25]:
np.array([1, 2, 3]) @ np.array([3, 2, 1])

10

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #F4330C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #F7C8C0; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Pozor</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Operace `C`*`C` násobí matice po prvcích (není to maticové násobení)!
</p>
</div>
</div>

In [54]:
# maticove nasobeni
print(np.dot(C,C), '\n')

# nasobeni po prvcich
print(C*C)

[[1856 2408]
 [4214 5468]] 

[[ 484  784]
 [2401 4096]]


**Reshape**

Funkce `reshape()` umožňuje změnit tvar pole/matice podle požadovaných rozměrů. Je třeba si ovšem dát pozor na *indexové pořadí*, podle kterého se prvky přerovnávají.

In [3]:
np.arange(1,17), np.reshape(np.arange(1,17), [4,4], order='F')  # pořadí indexů 'C' nebo 'F'

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]]))

### Matematické funkce

`numpy` obsahuje často používané funkce a konstanty (napr. `sqrt()`, `log()`, `log10()`, `sin()`, `abs()`, `e`, `pi`, ...):

In [4]:
print(np.sqrt(5))
print(np.log(5))
print(np.log10(5))
print(np.sin(5))
print(np.abs(-3))
print(np.e)
print(np.pi)

2.23606797749979
1.6094379124341003
0.6989700043360189
-0.9589242746631385
3
2.718281828459045
3.141592653589793


Součet prvků v poli je dán funkcí `sum()`:

In [5]:
np.sum(np.arange(0, 100, 3))    # součet čísel dělitelných třemi od 0 do 100 

1683

Minimální a maximální hodnotu v poli určíme funkcí `min()` a `max()`:

In [29]:
np.min(A), np.max(A)

(1, 6)

Polohu (index) minimální a maximální hodnoty v poli získáme pomocí funkce `argmin()` a `argmax()`:

In [28]:
np.argmin(A), np.argmax(A)

(0, 5)

### Další užitečné funkce

**Náhoda**

Pole náhodných čísel v rozmezí 0 az 1 se vygeneruje pomocí funkce `np.random.rand()`:

In [ ]:
np.random.rand(3,2)

array([[0.85196594, 0.66928364],
       [0.17104743, 0.51678847],
       [0.8152541 , 0.17603683]])

**Statistické funkce**

Funkce `average()` vrací průměrnou hodnotu; `std()` je směrodatná odchylka a `var()` je rozptyl:

In [ ]:
np.average(A)   # průměrná hodnota

3.5

In [ ]:
np.std(A)   # směrodaná odchylka (standard deviation)

1.707825127659933

In [ ]:
np.var(A)   # rozptyl (variance)

2.9166666666666665

**Práce se soubory** - můžete se dozvědět [zde](https://fjfi.pythonic.eu/posts/zaklady-numpy.html#Pr%C3%A1ce-se-soubory)

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #00843F; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #D6ECE1; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Tip</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Více se můžete dozvědet v [dokumentaci](https://numpy.org/doc/stable/reference/) nebo opět v kurzu [12PYTH](https://fjfi.pythonic.eu/posts/zaklady-numpy.html).
</p>
</div>
</div>

## Vizualizace dat - matplotlib.pyplot
* popis knihovny, k čemu je
* představení různých možností vizualizace

In [5]:
import matplotlib.pyplot as plt

**mgrid**

## Knihovna Scipy
* popis knihovny, na co se hodí
* nejužitěčnější funkce pro algebru, optimalizaci, NN, atd
* ukázka na příkladech z předchozích hodin - srovnání

## Bonus

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #E0B32C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #FFF3CD; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Úkol - bonus 1</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

Doplňte chybějící části označené `???` a opravte chyby, aby fungoval program na hru Oko bere (Black jack):
</p>
</div>
</div>

```
import random

soucet = 0
while ???:
    print('Máš', soucet, 'bodů')
    odpoved = input('Otočit kartu? ')
    if odpoved == 'ano':
        ??? = random.randrange(2, 11)
        print('Otočil/a jsi', karta)
        soucet = ???
    elif ???:
        break
    else:
        ???

if soucet == 21:
    print('Gratuluji! Vyhrál/a jsi!')
???
    print('Smůla!', soucet, 'bodů je moc!')
else:
    print('Chybělo jen', 21 - soucet, 'bodů!')
```    

<div style="margin-top: 25px; margin-bottom: 25px; padding-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; border-radius: 4px; border-color: #E0B32C; border-right-width: 1px; border-top-width: 1px; border-bottom-width: 1px; border-left-width: 3px; border-style: solid">
<div style="background: #FFF3CD; color: #000000; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; border-radius: 1px 3px 0px 0px; font-weight: 600">Úkol - bonus 2</div>
<div style="padding-left: 20px; padding-right: 20px; padding-top: 0px; padding-bottom: 0px; border-radius: 0px 0px 3px 3px">
<p>

? použít Python, numpy a scipy na nějakou z předchozích úloh..
</p>
</div>
</div>

## Další zdroje
* kde se naučit více, procvičit
* Pandas
* Tensorflow - jen zminit..
* Bonus úloha ?